runCrespZP_brain:
    state: 'active'
    tsel: 'response'
    layerlist: 'all'
    reftag: 'all'
    spec: 'zscore'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','Attention']#
    imetrics:
      features: []
      weights: []
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    rmetrics:
      features: 'all'#'all' or int, if  int the pcs up to int are considered
      weights: []
    utypes: ['ww']
    nnodes: 400
    clustering:
      ward: [5,6,7,8,9,10]


runCrespZI_brain:
    state: 'active'
    tsel: 'response'
    layerlist: 'all'
    reftag: 'all'
    spec: 'zscore'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','Attention']#
    imetrics:
      features: []
      weights: []
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    rmetrics:
      features: 'all'
      weights: []
    utypes: ['nw']
    nnodes: 220
    clustering:
      ward: [5,6,7,8,9,10]
