runC00dMP1:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    spec: 'dur1'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','Attention']#
    imetrics:
      features: ['B_mean','M_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 220
    clustering:
      ward: [5,6,7]


runC00dMI1:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    spec: 'dur1'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','Attention']#
    imetrics:
      features: ['B_mean','M_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 150
    clustering:
      ward: [5,6,7]


runC00dMP2:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    spec: 'dur2'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','Attention']#
    imetrics:
      features: ['B_mean','M_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 220
    clustering:
      ward: [5,6,7]


runC00dMI2:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    spec: 'dur2'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','Attention']#
    imetrics:
      features: ['B_mean','M_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 150
    clustering:
      ward: [5,6,7]


runC00dMP3:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    spec: 'dur3'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','Attention']#
    imetrics:
      features: ['B_mean','M_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 220
    clustering:
      ward: [5,6,7]


runC00dMI3:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    spec: 'dur3'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','Attention']#
    imetrics:
      features: ['B_mean','M_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 150
    clustering:
      ward: [5,6,7]