runC00dMP_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 700
    clustering:
      ward: [7]

runC00dMnLP_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 600
    clustering:
      ward: [7]

runC00dMnLI_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 300
    clustering:
      ward: [6,7,8]
      gmm: [7]

runC00dMLP_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Detection','Context']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 300
    clustering:
      ward: [6,7,8]
      gmm: [7]

runC00dMLI_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Detection','Context']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 150
    clustering:
      ward: [6,7,8]
      gmm: [7]