runA00d:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['IBL','Steinmetz','Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','IBL']#
    imetrics:
      features: ['B','LvR','rate']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 240 #280

runC00d:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B','LvR','rate']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 240 #280


runA01d:
    state: 'active'
    tsel: 'poststim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['IBL','Steinmetz','Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','IBL']#
    imetrics:
      features: ['B','LvR','rate']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 280 #280

runC01d:
    state: 'active'
    tsel: 'poststim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B','LvR','rate']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 280 #280


runAw:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['IBL','Steinmetz','Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','IBL']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: 'all'
    nnodes: 250 #280

runCw:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: 'all'
    nnodes: 250 #280

runAwP:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['IBL','Steinmetz','Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','IBL']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: ['ww']
    nnodes: 250 #280

runCwP:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: ['ww']
    nnodes: 250 #280
