runC00dP_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B','LvR','rate']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 350
    clustering:
      ward: [3,4,5,6,7]
      kmeans: [3,4,7]

runC00dI_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B','LvR','rate']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 100
    clustering:
      ward: [3,4,5,6,7]
      kmeans: [3,4,7]



