runC00dMP_M:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','M_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 220
    clustering:
      ward: [5,6,7]


runC00dMI_M:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','M_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 150
    clustering:
      ward: [5,6,7]

runC00dMP_LvR:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','LvR_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 220
    clustering:
      ward: [5,6,7]


runC00dMI_LvR:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','LvR_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 150
    clustering:
      ward: [5,6,7]

runC00dMP:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 220
    clustering:
      ward: [4,5,7,8]


runC00dMI:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 150
    clustering:
      ward: [3,4,5,6,7,8]

