runC00dMV:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','B_std','Rho_mean','Rho_std','rate_mean','rate_std']
      weights: [1,1,1,1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]


runC00dMV2:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','B_std','Rho_mean','Rho_std','rate_mean','rate_std','LvR_std','LvR_mean']
      weights: [1,1,1,1,1,1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]

runC00dMV3:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','B_std','Rho_mean','Rho_std']
      weights: [1,1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]

runC00dMVP:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','B_std','Rho_mean','Rho_std','rate_mean','rate_std']
      weights: [1,1,1,1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]


runC00dMV2P:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','B_std','Rho_mean','Rho_std','rate_mean','rate_std','LvR_std','LvR_mean']
      weights: [1,1,1,1,1,1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]

runC00dMV3P:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','B_std','Rho_mean','Rho_std']
      weights: [1,1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]


runC00dM:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]

runC00dMnL_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]

runC00dMnLP_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]

runC00dMnLI_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 300
    clustering:
      ward: [6,7,8]
      gmm: [7]

runC00dMLP_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Detection','Context']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 300
    clustering:
      ward: [6,7,8]
      gmm: [7]

runC00dMLI_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Detection','Context']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['nw']
    nnodes: 150
    clustering:
      ward: [6,7,8]
      gmm: [7]


runC00dMVnLP_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean','B_std','Rho_std','rate_std']
      weights: [1,1,1,0.5,0.5,0.5]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]


runC00dMVLP_brain:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Detection','Context']#
    imetrics:
      features: ['B_mean','Rho_mean','rate_mean','B_std','Rho_std','rate_std']
      weights: [1,1,1,0.5,0.5,0.5]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 600
    clustering:
      ward: [6,7,8]
      gmm: [7]