runC00d:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: ['B','LvR','rate']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 240 #280
    clustering:
      ward: [4,5,6]
      gmm: [4,7]
      kmeans: [2,5,7]

runC00dX:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'passive'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto']#
    imetrics:
      features: ['B','LvR','rate']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: 'all'
    nnodes: 200
    clustering:
      ward: [4,5,6]
      kmeans: [2,4]




runAw:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['IBL','Steinmetz','Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','IBL']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: 'all'
    nnodes: 250 #280
    clustering:
      ward: [2,3,5]

runCw:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: 'all'
    nnodes: 200 #280
    clustering:
      ward: [2,4,6,8]
      kmeans: [3,4,5]

runAwP:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['IBL','Steinmetz','Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','IBL']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: ['ww']
    nnodes: 250 #280
    clustering:
      ward: [5,6]
      kmeans: [5]

runCwP:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: ['ww']
    nnodes: 200 #280
    clustering:
      ward: [5]
      gmm: [4]

runSwP:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['IBL','Steinmetz']
    tasks: ['IBL']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: ['ww']
    nnodes: 220 #280
    clustering:
      ward: [4,5,7]
      gmm: [2,3]

runAwI:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['IBL','Steinmetz','Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context','IBL']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: ['nw']
    nnodes: 100 #280
    clustering:
      ward: [3,5,6]
      kmeans: [6]

runCwI:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['Carlen']
    tasks: ['Passive','Aversion','Opto','Detection','Context']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: ['nw']
    nnodes: 120 #280
    clustering:
      ward: [5]

runSwI:
    state: 'active'
    tsel: 'prestim'
    layerlist: 'all'
    reftag: 'all'
    datasets: ['IBL','Steinmetz']
    tasks: ['IBL']#
    imetrics:
      features: []#['B','LvR','rate']
      weights: []#[1,1,1]
    wmetrics:
      features: ['peak2Trough','abRatio','p2tRatio']
      weights: [1,1,1]
    utypes: ['nw']
    nnodes: 120 #280
    clustering:
      ward: [5]

