runIBLPasdM3_brain_pj: #_pj means projection
    state: ''
    tsel: 'passive'
    layerlist: 'all'
    reftag: 'all'
    spec: 'dur3'
    datasets: ['IBL_Passive']
    tasks: ['IBL_Passive']#
    imetrics:
      features: ['B_mean','M_mean','rate_mean']
      weights: [1,1,1]
    wmetrics:
      features: []#['peak2Trough','abRatio','p2tRatio']
      weights: []#[1,1,1]
    utypes: ['ww']
    nnodes: 400
    clustering:
      ward: [5,6,7]
    srcrun: 'runC00dM3_brain'# only give this for projections

